name: Daily RSS update

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC varje dag
  workflow_dispatch:        # Manuell trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run RSS diff
        run: python ingest/rss_watcher.py
      - name: Validate new documents
        run: pytest qa/schema_validator.py -v
